Vagrant.configure("2") do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  # Install Docker and docker compose (vagrant plugin install vagrant-docker-compose)
  config.vm.provision :docker
  config.vm.provision :docker_compose, compose_version: "1.29.0"

  # Quick fix problem with certificate
  config.vm.box_download_insecure=true

  # To avoid "insecure key detected"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
     v.name = "Mindento"
     v.memory = 7000
     v.cpus = 4
     v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
     v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end

  config.winrm.timeout = 1800

  config.vm.define "Mindento" do |node|
      node.vm.box = "ubuntu/bionic64"
      node.vm.boot_timeout = 1800

      node.vm.network "forwarded_port", guest: 80, host: 80 #http
      node.vm.network "forwarded_port", guest: 443, host: 443 #https
      node.vm.network "forwarded_port", guest: 3306, host: 3306 #database

      node.vm.hostname = "api.mindento.local"
      node.hostmanager.aliases = [
        "test.mindento.local",
        "proxy.mindento.local"
      ]

      node.vm.synced_folder "F:/DEV/mindento/Api", "/Core"
      node.vm.synced_folder "F:/DEV/mindento/Docker", "/Docker"

      node.vm.provision :shell, path: "provision.sh"
      node.vm.provision :shell, path: "up.sh", run: "always"
  end

end


